import './tasks/html.js';
import './tasks/sass.js';
import './tasks/images.js';
import './tasks/fonts.js';
import './tasks/files.js';
import './tasks/js.js';
import './tasks/server.js';
import './tasks/watch.js';
import './tasks/clean.js';
